default:
  image: registry.git.ku.dk/kuit-public/docker-tower-cli:latest
  before_script:
    - ansible --version
    # remove world write permissions to allow usage of ansible.cfg
    - chmod 750 ./
    - printf '[defaults]\nroles_path=../\n' > ansible.cfg

linting:
  script:
    - ansible-lint --profile production
