---
- name: Generate info tree of SAS devices
  block:
    - name: gather SAS controller based bindings
      sas_multipath_bindings:
        primary: "{{ dm_multipath_sas_controllers['primary'] | default(omit) }}"
        secondary: "{{ dm_multipath_sas_controllers['secondary'] | default(omit) }}"
  always:
    - name: print generated SAS controller structure
      debug:
        var: ansible_facts['sas_ctrls']
    - name: print generated SAS JBOD structure
      debug:
        var: ansible_facts['sas_jbods']

- name: Generate device name bindings
  template:
    src: templates/bindings.j2
    dest: /etc/multipath/bindings
    mode: "0755"
