---
- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install dm-multipath for {{ ansible_os_family }}
  include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Configure dm-multipath for {{ ansible_os_family }}
  include_tasks: "configure-{{ ansible_os_family }}.yml"

- name: "Enable and start service"
  systemd:
    name: '{{ multipath_service }}'
    state: 'started'
    enabled: yes
