---
- name: "Reload multipathd"
  debug: msg="rescan scsi bus first"
  changed_when: True
  notify:
    - "Rescan scsi bus"
    - "Reload multipathd - after scsi bus rescan"

- name: "Rescan scsi bus"
  command: "rescan-scsi-bus.sh"
  register: result
  changed_when: "result.rc != 0"
  check_mode: no

- name: "Reload multipathd - after scsi bus rescan"
  service:
    name: "{{ multipath_service }}"
    state: "reloaded"
